#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#polybar
$HOME/.config/polybar/launch.sh

#xset +fp /usr/share/fonts/siji
#xset fp rehash

/home/john/.local/bin/setmouseaccel

hdmi_active=$(xrandr | grep ' connected' | grep 'HDMI' | awk '{print $1}')

#wallpaper
nitrogen --restore --set-zoom-fill &

#set compositor
picom --experimental-backends --config /home/john/.config/picom/picom.conf &

#get the resources
#xrdb -merge ~/.Xresources

#sleep 0.1

#ensure nordvpn is running
#/home/john/.local/bin/checknord

#echo "$hdmi_active" > ~/idk.txt

if [[ ! -z "$hdmi_active" ]]; then
   xrandr --output eDP-1 --mode 1920x1080
   xrandr --output HDMI-1 --mode 1920x1080 --right-of eDP-1 --primary
   # xrandr --output HDMI1 --mode 1920x1080 --pos 0x0 --rotate normal --primary --right-of eDP1  --output eDP1 --mode 1920x1080 --pos 0x1080 --rotate normal
   sleep 0.1
   #xrandr --output HDMI-`1 --brightness 0.8

   xrdb -merge ~/.Xresources-hdmi
   # echo "plz" > /home/john/test.txt
   # bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 10
   bspc monitor "eDP-1" -d I II III IV V VI VII VIII IX X
   bspc monitor "HDMI-1" -d I II III IV V VI VII VIII IX X

   # bspc monitor HDMI1 -d 1 2 3 4 5 6 7 8 9 10

   # i=1
   # for monitor in $(bspc query -M | tac); do
   #    echo $monitor > /home/john/plzzz.txt
   #    bspc monitor $monitor -d $monitor/1 $monitor/2 $monitor/3 $monitor/4 $monitor/5 $monitor/6 $monitor/7 $monitor/8 $monitor/9 $monitor/10
   #    let i++
   # done

else
   xrandr --output "eDP-1" --mode 1920x1080
   bspc monitor "eDP-1" -d I II III IV V VI VII VIII IX X
   xrdb -merge ~/.Xresources
fi


# if [[ ! -z "$hdmi_active" ]]; then
#    xrandr --auto --output HDMI1 --mode 1920x1080 --right-of eDP1
# fi

#set monitor to the right
#xrandr --auto --output HDMI1 --mode 1920x1080 --right-of eDP1

#set screen resolution
#xrandr --output eDP-1 --scale 0.45x0.45

# bspc monitor -d I II III IV V VI VII VIII IX X

# if [[ ! -z "$hdmi_active" ]]; then
#     bspc monitor eDP1 -d VI VII VIII IX X
#     bspc monitor HDMI1 -d I II III IV V
# else
#     bspc monitor eDP1 -d I II III IV V VI VII VIII IX X
# fi


bspc config border_width         8
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc config focused_border_color \#EC6798

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled

#wmname LG3D
